In [17]:
import numpy as np;
matrix=np.array([[1,2,3],[4,5,6]]);
matrix=matrix.reshape(3,2);
matrix=np.array([[1,2,3,4,5],[6,7,8,9,10]]);
print(matrix)
matrix1=np.array([[1,2,3],[4,5,6]]);
matrix2=np.array([[5,6,7],[13,10,11]]);
subtraction_Of_matrix=matrix1+matrix2;
print(subtraction_Of_matrix);
reshape_matrix=subtraction_Of_matrix.reshape(3,2);
print(reshape_matrix)
scaler_multiple_matrix=matrix1*3;
print(f"Multiple-matrix",scaler_multiple_matrix);

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  8 10]
 [17 15 17]]
[[ 6  8]
 [10 17]
 [15 17]]
Multiple-matrix [[ 3  6  9]
 [12 15 18]]


In [26]:
list_array=np.array([2,4,7,8,9,5]);
print(list_array)
zeros__array=np.zeros(5);
print(zeros__array)
ones__arrays=np.ones(5);
print(ones__arrays)
transpose_array=np.transpose(5);
print(transpose_array)
arrange_array=np.arange(1,10,2);
arrange_array=np.arange(1,100,2);
print(sum(arrange_array));

[2 4 7 8 9 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
5
2500


In [28]:
import numpy as np;
arr1=np.array([1,2,3,4,5]);
arr2=np.array([5,4,3,2,1]);
additionOfArray=arr1+arr2;
multiplication=arr1*arr2;
divisionOfArray=arr1//arr2;
print(f'add:{additionOfArray}');
print(f'multiplication:{multiplication}');
print(f'division:{divisionOfArray}');

arr=np.array([10,20,30,40,50]);
slice_result=arr[1:5];
print(f'slice-result: {slice_result}');
step_slice_result=arr[::2];
print(f'step-slice-result:{step_slice_result}')


add:[6 6 6 6 6]
multiplication:[5 8 9 8 5]
division:[0 0 1 2 5]
slice-result: [20 30 40 50]
step-slice-result:[10 30 50]
