In [12]:
'''
=>advantage of using Numpy Arrays over Python Lists:
1.Consumes les memory
2.fast as compared to the python list
3.convenient to use
'''
List=[1,2,3,4,5,5];
import numpy as np;
a=np.array([1,2,3,4]);
print(a);
for i in a:print(i);
sum=0;
for i in a:
    sum=sum+i;
print(sum);
print(type(a))

#Data type storage
#Importing module
#Numerical operation
#Modification capabilities
#Consumes less memory
#fast as compared to the python list
#Convenient to use
%timeit [j**4 for j in range(1,9)];
%timeit np.arange(1,9)**4;
a=np.array([1,2,3,4,5]);
print(a);

[1 2 3 4]
1
2
3
4
10
<class 'numpy.ndarray'>
367 ns ± 1.97 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.39 μs ± 12.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
[1 2 3 4 5]


In [19]:
import numpy as np;
x=[1,2,3,4,5];
y=np.array(x);
print(y);
print(type(y))
L=[];
for i in range(1,5):
    int_1=input('enter value');
    int_1=int(int_1);
    L.append(int_1);
print(np.array(L));
    

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4]


In [25]:
'''
1.1-D arrays
2.2-D arrays
3.3-D arrays
4.Higher Dimension arrays
'''
##1-dimension array
a=[1,2,3,4,5,6,7];
##2-dimension array
b=[[1,2,3,4],[5,6,7,8]]
##3-dimension array
c=[[[1,2,3],[4,5,6],[7,8,9]]]

od1=np.array(a);
td1=np.array(b);
three_d1=np.array(c);
print(od1.ndim);
print(td1.ndim);
print(three_d1.ndim);


arn=np.array([1,2,3,4],ndmin=5);
print(arn);
print(arn.ndim)

1
2
3
[[[[[1 2 3 4]]]]]
5


In [ ]:
'''
Special Numpy Array
=>Array filled with 0's
=>Array filled with 1's
=>Create and empty array
=>An array with a range of elements
=>Array diagonal element filled with 1's
=>Create an array with values that are spaced linearly in a  specified interval
'''
import numpy as np;
ar_zero=np.zeros(4);
arr_d2=np.zeros((3,4))
print(arr_d2);
oned_num=np.ones(3)
oned_num=np.ones((3,3))
print(oned_num)
empty_numpy_arr=np.empty(4);
empty_numpy_arr=np.empty((4,4))
print(empty_numpy_arr)
arr_rn=np.array(4);
print(arr_rn);
##diagonal numpy array
ar_digonal=np.eye(3,5);
print(ar_digonal)
##Line space 
ar_line=np.linspace(1,10,num=5);
print(ar_line);



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 2.12199579e-314]]
4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[ 1.    3.25  5.5   7.75 10.  ]
[]


In [57]:
##Create numpy arrays with random arrays
##functions
'''
1.rand():the function is used to generate a random value between 0 to 1
2.randn():the function is used to generate a random value close to zero.This 
may return positive or negative numbers as well
3.ranf():The function for doing random sampling in numpy.It
return an array of specified shape and fills it with random floats in the half-open 
interval[0.0,1,.0]
4.randint():The function is used to generate a  random number between a given number
'''

##rand()
import numpy as np;
var=np.random.rand(4);##One dimension
print(var);
print("**********")
var1=np.random.rand(2,5)##two dimension
print(var1);
print("**********")
##randn()
var2=np.random.randn(5)##One dimension
print(var2);
print("**********")
var3=np.random.rand(2,5);##2-d array
print(var3);
print("**********")
##ranf()
var4=np.random.ranf(5);##1-d array
print(var4);
print("**********")
##randint()
var5=np.random.randint(4);
max=20
min=5;
t=5
var5=np.random.randint(min,max,t)
var5=np.random.randint(1,100,5);
print(var5)


[0.42172247 0.3705062  0.41742425 0.74283847]
**********
[[0.39808746 0.77592541 0.55873457 0.47283546 0.03521741]
 [0.59276748 0.61575542 0.75938068 0.93127234 0.63693907]]
**********
[ 1.28313955 -1.58435235 -0.54837108 -0.56162513  0.46835807]
**********
[[0.89674724 0.13843134 0.27227279 0.85163425 0.05856006]
 [0.21212103 0.60646817 0.42224981 0.1437635  0.99076682]]
**********
[0.26662043 0.76011497 0.2114793  0.9753527  0.92236378]
**********
[91 83 58 67 59]
